name: Set up dependencies
description: 'Install dependencies per platform'

inputs:
  cibuildwheel:
    type: choice
    description: "cibuildwheel run"
    options:
      - 'cp38'
      - 'cp39'
      - 'cp310'
      - 'cp311'
    default: 'cp39'

runs:
  using: 'composite'
  steps:
    ################
    # Dependencies #
    ################
    - name: Install python dependencies
      shell: bash
      run: make requirements
      if: ${{ runner.os == 'Linux' }}

    ################
    # Linux # NOTE: skip for manylinux image
    # - name: Linux init steps
    #   shell: bash
    #   run: make dependencies-vcpkg
    #   if: ${{ runner.os == 'Linux' }} # skip

    ################
    # Mac
    - name: Mac init steps
      shell: bash
      run: make dependencies-mac
      if: ${{ runner.os == 'macOS' }}

    # - name: Setup vcpkg cache in shell
    #   shell: bash
    #   run: |
    #     which -a gcc-12
    #     echo "CC=/usr/local/bin/gcc-12" >> $GITHUB_ENV
    #     echo "CMAKE_C_COMPILER=/usr/local/bin/gcc-12" >> $GITHUB_ENV
    #     echo "CXX=/usr/local/bin/g++-12" >> $GITHUB_ENV
    #     echo "CMAKE_CXX_COMPILER=/usr/local/bin/g++-12" >> $GITHUB_ENV
    #   if: ${{ runner.os == 'macOS' }}

    ################
    # Windows
    - name: Windows init steps (vc143)
      shell: bash
      # run: make dependencies-win
      run: |
              Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
              choco install make -y
              choco install cmake -y
              choco install winflexbison3 -y
              choco install zip -y
              choco install unzip -y
              choco install tartool -y
              New-Alias -Name bison -Value win_bison
              New-Alias -Name flex -Value win_flex
      env:
        VCPKG_DEFAULT_TRIPLET: x64-windows
        VCPKG_PLATFORM_TOOLSET: v143
      if: ${{ runner.os == 'Windows' }}
