name: Set up dependencies
description: 'Install dependencies per platform'

inputs:
  cibuildwheel:
    type: choice
    description: "cibuildwheel run"
    options:
      - 'cp38'
      - 'cp39'
      - 'cp310'
      - 'cp311'
      - 'cp312'
    default: 'cp39'

runs:
  using: 'composite'
  steps:
    ################
    # Dependencies #
    ################
    - name: Install python dependencies
      shell: bash
      run: make requirements

    ################
    # Linux # NOTE: skip for manylinux image
    # - name: Linux init steps
    #   shell: bash
    #   run: make dependencies-vcpkg
    #   if: ${{ runner.os == 'Linux' }} # skip

    ################
    # Mac
    - name: Mac init steps
      shell: bash
      run: make dependencies-mac
      if: ${{ runner.os == 'macOS' }}

    # - name: Setup vcpkg cache in shell
    #   shell: bash
    #   run: |
    #     which -a gcc-12
    #     echo "CC=/usr/local/bin/gcc-12" >> $GITHUB_ENV
    #     echo "CMAKE_C_COMPILER=/usr/local/bin/gcc-12" >> $GITHUB_ENV
    #     echo "CXX=/usr/local/bin/g++-12" >> $GITHUB_ENV
    #     echo "CMAKE_CXX_COMPILER=/usr/local/bin/g++-12" >> $GITHUB_ENV
    #   if: ${{ runner.os == 'macOS' }}

    ################
    # Windows
    - name: Windows init steps (vc143)
      shell: bash
      run: make dependencies-win
      env:
        VCPKG_DEFAULT_TRIPLET: x64-windows-static-md
        VCPKG_PLATFORM_TOOLSET: v143
      if: ${{ runner.os == 'Windows' }}
