cmake_minimum_required(VERSION 3.7.2)

if (CSP_USE_VCPKG)
  find_package(RdKafka CONFIG REQUIRED)
  find_package(unofficial-avro-cpp CONFIG REQUIRED)
  if(NOT WIN32)
    # Bad, but a temporary workaround for
    # https://github.com/microsoft/vcpkg/issues/40320
    link_directories(${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib)
  endif()
  set(AVRO_LIBRARIES unofficial::avro-cpp::avrocpp CACHE INTERNAL "")
  set(DepsKafkaAdapter_FOUND TRUE)
else()
  find_package(RdKafka REQUIRED)
  find_package(Avro)
  if(NOT Avro_FOUND)
    set(DepsKafkaAdapter_FOUND FALSE)
  else()
    set(AVRO_LIBRARIES Avro::avrocpp CACHE INTERNAL "")
    set(DepsKafkaAdapter_FOUND TRUE)
  endif()
endif()
