cmake_minimum_required(VERSION 3.7.2)

if (CSP_USE_VCPKG)
  find_package(RdKafka CONFIG REQUIRED)
  find_package(unofficial-avro-cpp CONFIG REQUIRED)
  set(CSP_HAVE_AVRO ON)
  if(NOT WIN32)
    # Bad, but a temporary workaround for
    # https://github.com/microsoft/vcpkg/issues/40320
    link_directories(${VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib)
  endif()
else()
  find_package(RdKafka REQUIRED)
  find_package(Avro QUIET)
  if(Avro_FOUND)
    set(CSP_HAVE_AVRO ON)
  else()
    set(CSP_HAVE_AVRO OFF)
    message(STATUS "Avro not found - AVRO protocol support will be disabled")
  endif()
endif()
