cmake_minimum_required(VERSION 3.7.2)

if (CSP_USE_VCPKG)
  find_package(RdKafka CONFIG REQUIRED)
else()
  find_package(RdKafka REQUIRED)
  pkg_check_modules(SASL libsasl2)
  if(SASL_FOUND)
    set(CSP_LINK_SASL ON)
  else()
    set(CSP_LINK_SASL OFF)
  endif()
endif()
find_package(OpenSSL REQUIRED)
find_package(lz4 REQUIRED)
