"""Type stubs for csp.event_loop.bridge module."""

import asyncio
from datetime import datetime, timedelta
from typing import Any, Callable, Coroutine, Optional, TypeVar

from csp.impl.genericpushadapter import GenericPushAdapter

_T = TypeVar("_T")

class AsyncioBridge:
    """Bridge between asyncio and running CSP graphs."""

    def __init__(self, adapter_type: type = object, name: str = "asyncio_bridge") -> None: ...
    @property
    def adapter(self) -> GenericPushAdapter: ...
    @property
    def is_running(self) -> bool: ...
    @property
    def loop(self) -> Optional[asyncio.AbstractEventLoop]: ...
    def start(self, start_time: Optional[datetime] = None) -> None: ...
    def stop(self, timeout: float = 5.0) -> None: ...
    def push(self, value: Any) -> bool: ...
    def call_soon(self, callback: Callable[..., Any], *args: Any) -> None: ...
    def call_later(self, delay: float, callback: Callable[..., Any], *args: Any) -> asyncio.TimerHandle: ...
    def call_at(self, when: datetime, callback: Callable[..., Any], *args: Any) -> asyncio.TimerHandle: ...
    def call_at_offset(self, offset: timedelta, callback: Callable[..., Any], *args: Any) -> asyncio.TimerHandle: ...
    def run_coroutine(self, coro: Coroutine[Any, Any, _T]) -> asyncio.Future[_T]: ...
    def time(self) -> float: ...
    def elapsed_since_start(self) -> timedelta: ...
    def wait_for_adapter(self, timeout: Optional[float] = None) -> bool: ...

class BidirectionalBridge(AsyncioBridge):
    """Bridge supporting bidirectional communication."""

    def __init__(self, adapter_type: type = object, name: str = "bidi_bridge") -> None: ...
    def on_event(self, callback: Callable[[Any], None]) -> None: ...
    def off_event(self, callback: Callable[[Any], None]) -> bool: ...
    def emit(self, value: Any) -> None: ...
