"""Type stubs for csp Edge class."""

from typing import Any, TypeVar

from csp.impl.types.tstype import TsType

T = TypeVar("T")

class Edge:
    """
    Represents a connection (edge) in the csp graph between nodes.

    Edges are created when connecting nodes together and represent
    the flow of time series data through the graph.
    """

    tstype: TsType[Any]
    nodedef: Any
    output_idx: int
    basket_idx: int

    def __init__(
        self,
        tstype: TsType[T],
        nodedef: Any,
        output_idx: int,
        basket_idx: int = ...,
    ) -> None: ...
    def __repr__(self) -> str: ...
    def __hash__(self) -> int: ...

    # Arithmetic operations
    def __add__(self, other: Any) -> "Edge": ...
    def __radd__(self, other: Any) -> "Edge": ...
    def __sub__(self, other: Any) -> "Edge": ...
    def __rsub__(self, other: Any) -> "Edge": ...
    def __mul__(self, other: Any) -> "Edge": ...
    def __rmul__(self, other: Any) -> "Edge": ...
    def __truediv__(self, other: Any) -> "Edge": ...
    def __rtruediv__(self, other: Any) -> "Edge": ...
    def __floordiv__(self, other: Any) -> "Edge": ...
    def __rfloordiv__(self, other: Any) -> "Edge": ...
    def __mod__(self, other: Any) -> "Edge": ...
    def __rmod__(self, other: Any) -> "Edge": ...
    def __pow__(self, other: Any) -> "Edge": ...
    def __rpow__(self, other: Any) -> "Edge": ...
    def __neg__(self) -> "Edge": ...
    def __pos__(self) -> "Edge": ...
    def __abs__(self) -> "Edge": ...

    # Comparison operations
    def __lt__(self, other: Any) -> "Edge": ...
    def __le__(self, other: Any) -> "Edge": ...
    def __gt__(self, other: Any) -> "Edge": ...
    def __ge__(self, other: Any) -> "Edge": ...
    def __eq__(self, other: Any) -> "Edge": ...  # type: ignore[override]
    def __ne__(self, other: Any) -> "Edge": ...  # type: ignore[override]

    # Bitwise operations
    def __and__(self, other: Any) -> "Edge": ...
    def __rand__(self, other: Any) -> "Edge": ...
    def __or__(self, other: Any) -> "Edge": ...
    def __ror__(self, other: Any) -> "Edge": ...
    def __xor__(self, other: Any) -> "Edge": ...
    def __rxor__(self, other: Any) -> "Edge": ...
    def __invert__(self) -> "Edge": ...

    # Attribute access for struct fields
    def __getattr__(self, name: str) -> "Edge": ...
