"""Type stubs for csp time series types."""

from typing import Any, Dict, Generic, List, Protocol, TypeVar, Union

T = TypeVar("T")
K = TypeVar("K")

class TsType(Protocol[T]):
    """
    The core time series type in csp.

    Usage:
        ts[int]      # A time series of integers
        ts[float]    # A time series of floats
        ts[MyStruct] # A time series of custom Struct types
    """

    typ: type

    def __class_getitem__(cls, params: Any) -> "TsType[Any]": ...

    # Arithmetic operations
    def __add__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __radd__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __sub__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __rsub__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __mul__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __rmul__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __truediv__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __rtruediv__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __floordiv__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __rfloordiv__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __mod__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __rmod__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __pow__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __rpow__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __neg__(self) -> "TsType[T]": ...
    def __pos__(self) -> "TsType[T]": ...
    def __abs__(self) -> "TsType[T]": ...

    # Comparison operations
    def __lt__(self, other: Union[T, "TsType[T]"]) -> "TsType[bool]": ...
    def __le__(self, other: Union[T, "TsType[T]"]) -> "TsType[bool]": ...
    def __gt__(self, other: Union[T, "TsType[T]"]) -> "TsType[bool]": ...
    def __ge__(self, other: Union[T, "TsType[T]"]) -> "TsType[bool]": ...
    def __eq__(self, other: Union[T, "TsType[T]"]) -> "TsType[bool]": ...  # type: ignore[override]
    def __ne__(self, other: Union[T, "TsType[T]"]) -> "TsType[bool]": ...  # type: ignore[override]

    # Bitwise operations
    def __and__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __rand__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __or__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __ror__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __xor__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __rxor__(self, other: Union[T, "TsType[T]"]) -> "TsType[T]": ...
    def __invert__(self) -> "TsType[T]": ...

# The ts type is an alias for TsType
ts = TsType

class DynamicBasketMeta(type):
    """Metaclass for DynamicBasket that enables [] syntax."""
    def __getitem__(cls, args: tuple[Any, Any]) -> Dict[TsType[Any], TsType[Any]]: ...

class DynamicBasket(metaclass=DynamicBasketMeta):
    """
    A dynamic basket type that maps time series keys to time series values.

    Usage:
        DynamicBasket[str, int]  # Maps ts[str] keys to ts[int] values
    """

    ...

def isTsType(t: Any) -> bool:
    """Check if the given type is a TsType."""
    ...

def isTsBasket(t: Any) -> bool:
    """Check if the given type is a time series basket (List[ts[T]] or Dict[K, ts[T]])."""
    ...

def isTsDynamicBasket(t: Any) -> bool:
    """Check if the given type is a dynamic basket (Dict[ts[K], ts[V]])."""
    ...

def isTsStaticBasket(t: Any) -> bool:
    """Check if the given type is a static basket."""
    ...

class GenericTSTypes(Generic[T]):
    """
    Utility class for generic ts type decoration.

    Available types:
        GenericTSTypes['T'].T_VAR - a 'T' type var
        GenericTSTypes['T'].TS_TYPE - a time series with values of 'T' type
        GenericTSTypes['T'].TS_LIST_BASKET_TYPE - a list basket
        GenericTSTypes['T'].TS_DICT_BASKET_TYPE - a dict basket
        GenericTSTypes['T'].TS_OR_BASKET_TYPE - ts or any basket
    """

    T_VAR: TypeVar
    TS_TYPE: TsType[T]
    TS_LIST_BASKET_TYPE: List[TsType[T]]
    TS_DICT_BASKET_TYPE: Dict[str, TsType[T]]
    TS_OR_BASKET_TYPE: Union[TsType[T], List[TsType[T]], Dict[str, TsType[T]]]

class SnapType(Generic[T]):
    """
    Snap type for capturing current value at graph build time.

    Usage:
        def my_node(x: csp.snap[ts[int]]) -> ...
    """
    def __init__(self, edge: TsType[T]) -> None: ...
    @property
    def edge(self) -> TsType[T]: ...
    @property
    def ts_type(self) -> TsType[T]: ...

class SnapKeyType:
    """Snapkey type for capturing dynamic basket keys."""
    def __init__(self) -> None: ...
    @property
    def key_tstype(self) -> TsType[Any]: ...

class AttachType(Generic[T]):
    """Attach type for dynamic basket attachment."""
    def __init__(self) -> None: ...
    @property
    def key_tstype(self) -> TsType[Any]: ...
    @property
    def value_tstype(self) -> TsType[T]: ...
