name: Publish Docs

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
      - "README.md"
  workflow_dispatch:

concurrency:
  group: docs
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Upload Documentation to Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@1bbb4280446f9630e8e21a18012cbacf3b0f992e  # v5.0.6
        with:
          path: docs/wiki
